spring:
  datasource:
    url: jdbc:h2:file:./data/lightning-trade
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html

# 交易配置
trading:
  markets:
    us:
      name: "US Market"
      enabled: true
      strategy:
        type: "DOUBLE_MA"
        shortPeriod: 5
        longPeriod: 20
      symbols:
        AAPL:
          code: "AAPL"
          lotSize: 100
        TSLA:
          code: "TSLA"
          lotSize: 100
    hk:
      name: "HK Market"
      enabled: true
      strategy:
        type: "BOLL"
        shortPeriod: 20
        kValue: 2.0
      symbols:
        "00700":
          code: "00700"
          lotSize: 100
        "09988":
          code: "09988"
          lotSize: 100

# 日志配置
logging:
  level:
    root: INFO
    com.lightningtrade.easyquant: DEBUG
  file:
    name: logs/lightning-trade.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"